/**
 * Contextual help — terminology tooltips (first-use onboarding follow-up).
 *
 * Unobtrusive (?) affordances, each with a 1–3 sentence explanation, so
 * remembering what "Coverage" or "Narrative Cluster" means never requires
 * replaying the guided tour. Explanations state what the thing IS in the
 * product; they never editorialize about content or perspectives.
 *
 * DOM rules: everything built via createElement (youtube.com enforces
 * TrustedHTML); toggle on click; one tooltip open at a time.
 */

export type HelpTopic =
  | 'viewpoint'
  | 'viewstream'
  | 'viewlist'
  | 'coverage'
  | 'autopsy'
  | 'time-machine'
  | 'exposure-budget'
  | 'assumption'
  | 'narrative-cluster'
  | 'source-type'
  | 'exploration'
  | 'provenance';

export const HELP_TOPIC_TEXT: Record<HelpTopic, string> = {
  viewpoint:
    'A saved set of instructions for discovery: what to look for and how the resulting feed should be shaped. You author it; every field is visible and editable.',
  viewstream:
    'The feed generated by activating a Viewpoint. It is composed through that lens\u2019s rules, and every inclusion is traceable through its provenance chain.',
  viewlist:
    'A named group of Viewpoints, so you can organize lenses by subject. Membership is by id; deleting a Viewpoint just removes it from its lists.',
  coverage:
    'A description of what the current pool/feed contains and omits: counts per topic, source type, narrative cluster, temporal position, and more. Descriptive only — it never tells you what to think about the balance.',
  autopsy:
    'A set of measurements of a composed Viewstream: concentration by channel and source, topic distribution, familiarity, temporal spread, exploration share, and budget compliance. Facts about composition, not judgments.',
  'time-machine':
    'Compares how the same subject was covered in different time periods relative to an anchor date you set. Descriptive only — it never claims causes or effects.',
  'exposure-budget':
    'Visible, editable bounds on how a Viewstream spends its slots: caps on single-channel or single-narrative share, minimums for unfamiliar or alternate-source material, cooldowns. Floors the live pool cannot satisfy are reported as violated, never manufactured.',
  assumption:
    'A note you wrote for a Viewpoint — context or instructions for that lens. Assumptions belong to the Viewpoint, never to your identity, and never silently influence ranking.',
  'narrative-cluster':
    'A classification dimension grouping candidates that share a narrative treatment of a subject. Many candidates have none recorded — reported as Unknown, never guessed.',
  'source-type':
    'A classification of where material comes from (publication, official source, independent creator, primary source, etc.). When the evidence does not support a classification, it stays Unknown.',
  exploration:
    'The share of a Viewstream reserved for material outside the Viewpoint\u2019s explicit seeds, so a lens does not collapse onto its own query results.',
  provenance:
    'The recorded chain behind every feed item: Viewpoint rule, discovery (provider, method, seed), classification, ranking components, and the composer\u2019s inclusion decision.',
};

/** Render a (?) button toggling the topic's explanation. */
export function renderHelpToggle(topic: HelpTopic): HTMLElement {
  const wrap = document.createElement('span');
  wrap.className = 'metube-help';
  const btn = document.createElement('button');
  btn.type = 'button';
  btn.className = 'metube-help-btn';
  btn.textContent = '?';
  btn.setAttribute('aria-label', `What is this? (${topic})`);
  btn.addEventListener('click', (event) => {
    event.stopPropagation();
    const existing = document.querySelector('.metube-help-pop');
    if (existing) existing.remove();
    const pop = document.createElement('span');
    pop.className = 'metube-help-pop';
    pop.textContent = HELP_TOPIC_TEXT[topic];
    wrap.append(pop);
  });
  wrap.append(btn);
  return wrap;
}

/** Remove any open tooltip (called on shell re-render / outside click). */
export function dismissHelpPopups(): void {
  document.querySelectorAll('.metube-help-pop').forEach((el) => el.remove());
}